// Package admin Code generated by swaggo/swag. DO NOT EDIT
package admin

import "github.com/swaggo/swag"

const docTemplateadmin = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "create admin",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.ReqUpsertAdmin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.RespAdmin"
                        }
                    }
                }
            }
        },
        "/admin/{name}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "get admin info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "admin name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.RespAdmin"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "update admin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "admin name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.ReqUpsertAdmin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.RespAdmin"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "delete admin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "admin name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/admin_permission": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "create admin permission",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.ReqUpsertAdminPermission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.AdminPermission"
                        }
                    }
                }
            }
        },
        "/admin_permission/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "get admin permission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "admin permission id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.AdminPermission"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "update admin permission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "admin permission id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.ReqUpsertAdminPermission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.AdminPermission"
                        }
                    }
                }
            }
        },
        "/admin_permission_group": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "create admin permission group",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.ReqUpsertAdminPermissionGroup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.AdminPermissionGroup"
                        }
                    }
                }
            }
        },
        "/admin_permission_group/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "get admin permission group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "admin permission group id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.AdminPermissionGroup"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "update admin permission group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "admin permission group id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.ReqUpsertAdminPermissionGroup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.AdminPermissionGroup"
                        }
                    }
                }
            }
        },
        "/admin_permission_groups": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "query admin permission groups",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity_admin.AdminPermissionGroup"
                            }
                        }
                    }
                }
            }
        },
        "/admin_permissions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "query admin permissions",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity_admin.AdminPermission"
                            }
                        }
                    }
                }
            }
        },
        "/admin_role": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "create admin role",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.ReqUpsertAdminRole"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.AdminRole"
                        }
                    }
                }
            }
        },
        "/admin_role/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "get admin role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "admin role id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.AdminRole"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "update admin role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "admin role id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.ReqUpsertAdminRole"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.AdminRole"
                        }
                    }
                }
            }
        },
        "/admin_roles": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "query admin roles",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity_admin.AdminRole"
                            }
                        }
                    }
                }
            }
        },
        "/admins": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "query admins",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity_admin.RespAdmin"
                            }
                        }
                    }
                }
            }
        },
        "/auth": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "two step auth",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity_admin.ReqAuth"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.RespAuth"
                        }
                    }
                }
            }
        },
        "/auth/google_auth_secret/{name}": {
            "get": {
                "tags": [
                    "auth"
                ],
                "summary": "get google auth secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.RespGoogleAuth"
                        }
                    }
                }
            }
        },
        "/auth/reset_password": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "reset password",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity_admin.ReqResetPassword"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/deposit_amount_total": {
            "get": {
                "description": "Get deposit amount total",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deposit"
                ],
                "summary": "Get deposit amount total",
                "parameters": [
                    {
                        "type": "string",
                        "description": "2006-01-06 00:00:00",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "2006-01-06 23:59:59",
                        "name": "end_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity_admin.RespGetDepositWithdrawTotal"
                            }
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "login",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity_admin.ReqLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.RespLogin"
                        }
                    }
                }
            }
        },
        "/pools": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "query pool",
                "parameters": [
                    {
                        "type": "string",
                        "description": "base_symbol",
                        "name": "base_symbol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "base_contract",
                        "name": "base_contract",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "quote_symbol",
                        "name": "quote_symbol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "quote_contract",
                        "name": "quote_contract",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity_admin.RespPool"
                            }
                        }
                    }
                }
            }
        },
        "/token": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "token"
                ],
                "summary": "create token",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.ReqCreateToken"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.RespToken"
                        }
                    }
                }
            }
        },
        "/token/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "pool"
                ],
                "summary": "update pool",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pool_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.ReqUpsertPool"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/entity_admin.RespPool"
                        }
                    }
                }
            }
        },
        "/user-passkeys/{uid}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "get user passkeys",
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity_admin.RespPasskey"
                            }
                        }
                    }
                }
            }
        },
        "/user_transactions_records": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "query transactions record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "symbol",
                        "name": "symbol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "chain_name",
                        "name": "chain_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "uid",
                        "name": "uid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "tx_hash",
                        "name": "tx_hash",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "login_method",
                        "name": "login_method",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_time",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_time",
                        "name": "end_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.TransactionsRecord"
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "query users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "uid",
                        "name": "uid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "login_method",
                        "name": "login_method",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_time",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "end_time",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity_admin.RespUser"
                            }
                        }
                    }
                }
            }
        },
        "/users_statis": {
            "get": {
                "description": "Get users statis",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "depth"
                ],
                "summary": "Get users statis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "month week day",
                        "name": "time_dimension",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "add_user_count add_passkey_count add_evm_count add_deposit_count",
                        "name": "data_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "amount",
                        "name": "amount",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "users statis",
                        "schema": {
                            "$ref": "#/definitions/db.UsersStatis"
                        }
                    }
                }
            }
        },
        "/withdraw_amount_total": {
            "get": {
                "description": "Get withdraw amount total",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deposit"
                ],
                "summary": "Get withdraw amount total",
                "parameters": [
                    {
                        "type": "string",
                        "description": "2006-01-06 00:00:00",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "2006-01-06 23:59:59",
                        "name": "end_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity_admin.RespGetDepositWithdrawTotal"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "db.LoginMethod": {
            "type": "string",
            "enum": [
                "google",
                "apple",
                "telegram",
                "evm"
            ],
            "x-enum-varnames": [
                "LoginMethodGoogle",
                "LoginMethodApple",
                "LoginMethodTelegram",
                "LoginMethodEVM"
            ]
        },
        "db.PoolStatus": {
            "type": "integer",
            "enum": [
                0,
                1
            ],
            "x-enum-varnames": [
                "PoolStatusClosed",
                "PoolStatusOpen"
            ]
        },
        "db.TransactionsRecord": {
            "type": "object",
            "properties": {
                "coin_name": {
                    "type": "string"
                },
                "deposit_amount": {
                    "type": "number"
                },
                "deposit_at": {
                    "type": "string"
                },
                "deposit_chain": {
                    "type": "string"
                },
                "evm_address": {
                    "type": "string"
                },
                "fee": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "symbol": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "withdraw_amount": {
                    "type": "number"
                },
                "withdraw_at": {
                    "type": "string"
                },
                "withdraw_chain": {
                    "type": "string"
                }
            }
        },
        "db.UsersStatis": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "period": {
                    "type": "string"
                }
            }
        },
        "entity.Chain": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "integer"
                },
                "chain_name": {
                    "type": "string"
                },
                "exsat_token_address": {
                    "type": "string"
                },
                "exsat_withdraw_fee": {
                    "type": "string"
                },
                "min_deposit_amount": {
                    "type": "string"
                },
                "min_withdraw_amount": {
                    "type": "string"
                },
                "withdraw_fee": {
                    "type": "string"
                }
            }
        },
        "entity.TokenInfo": {
            "type": "object",
            "properties": {
                "circulating_supply": {
                    "type": "string"
                },
                "fully_diluted_market_cap": {
                    "type": "string"
                },
                "historical_high": {
                    "type": "string"
                },
                "historical_high_date": {
                    "type": "string"
                },
                "historical_low": {
                    "type": "string"
                },
                "historical_low_date": {
                    "type": "string"
                },
                "intro": {
                    "type": "string"
                },
                "issue_date": {
                    "type": "string"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.TokenLink"
                    }
                },
                "market_capitalization": {
                    "type": "string"
                },
                "market_dominance": {
                    "type": "string"
                },
                "maximum_supply": {
                    "type": "string"
                },
                "rank": {
                    "type": "string"
                },
                "total_supply": {
                    "type": "string"
                },
                "volume": {
                    "type": "string"
                },
                "volume_div_market_cap": {
                    "type": "string"
                }
            }
        },
        "entity.TokenLink": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "entity_admin.AdminPermission": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity_admin.AdminPermissionAction"
                    }
                },
                "display_name": {
                    "type": "string"
                },
                "group": {
                    "$ref": "#/definitions/entity_admin.AdminPermissionGroup"
                },
                "id": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "entity_admin.AdminPermissionAction": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "entity_admin.AdminPermissionGroup": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity_admin.AdminPermission"
                    }
                }
            }
        },
        "entity_admin.AdminRole": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity_admin.AdminPermission"
                    }
                }
            }
        },
        "entity_admin.ReqAuth": {
            "type": "object",
            "required": [
                "key"
            ],
            "properties": {
                "google_verify_code": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                }
            }
        },
        "entity_admin.ReqCreateToken": {
            "type": "object",
            "properties": {
                "block_num": {
                    "type": "integer"
                },
                "chains": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Chain"
                    }
                },
                "decimals": {
                    "type": "integer"
                },
                "eos_contract": {
                    "type": "string"
                },
                "evm_contract": {
                    "type": "string"
                },
                "icon_url": {
                    "type": "string"
                },
                "info": {
                    "$ref": "#/definitions/entity.TokenInfo"
                },
                "max_supply": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "withdraw_fee": {
                    "type": "string"
                }
            }
        },
        "entity_admin.ReqLogin": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "entity_admin.ReqResetPassword": {
            "type": "object",
            "required": [
                "name",
                "new_password"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 30
                },
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "entity_admin.ReqUpsertAdmin": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "real_name": {
                    "type": "string"
                },
                "role_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "entity_admin.ReqUpsertAdminPermission": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity_admin.AdminPermissionAction"
                    }
                },
                "display_name": {
                    "type": "string"
                },
                "group_id": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "entity_admin.ReqUpsertAdminPermissionGroup": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "entity_admin.ReqUpsertAdminRole": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "permission_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "entity_admin.ReqUpsertPool": {
            "type": "object",
            "required": [
                "base_contract",
                "base_symbol",
                "pool_id",
                "quote_contract",
                "quote_symbol",
                "status",
                "visible"
            ],
            "properties": {
                "base_contract": {
                    "type": "string"
                },
                "base_symbol": {
                    "type": "string"
                },
                "pool_id": {
                    "type": "integer"
                },
                "quote_contract": {
                    "type": "string"
                },
                "quote_symbol": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/db.PoolStatus"
                },
                "visible": {
                    "type": "boolean"
                }
            }
        },
        "entity_admin.RespAdmin": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_login": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "real_name": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity_admin.AdminRole"
                    }
                }
            }
        },
        "entity_admin.RespAuth": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "integer"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity_admin.AdminRole"
                    }
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "entity_admin.RespGetDepositWithdrawTotal": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "entity_admin.RespGoogleAuth": {
            "type": "object",
            "properties": {
                "qr_data": {
                    "type": "string"
                },
                "secret": {
                    "type": "string"
                }
            }
        },
        "entity_admin.RespLogin": {
            "type": "object",
            "properties": {
                "is_first_login": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                }
            }
        },
        "entity_admin.RespPasskey": {
            "type": "object",
            "properties": {
                "is_auto": {
                    "type": "boolean"
                },
                "last_used_at": {
                    "type": "string"
                },
                "last_used_ip": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "signin_at": {
                    "type": "string"
                },
                "storage": {
                    "type": "string"
                },
                "synced": {
                    "type": "boolean"
                }
            }
        },
        "entity_admin.RespPool": {
            "type": "object",
            "properties": {
                "base_contract": {
                    "type": "string"
                },
                "base_symbol": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "quote_contract": {
                    "type": "string"
                },
                "quote_symbol": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/db.PoolStatus"
                },
                "updated_at": {
                    "type": "string"
                },
                "visible": {
                    "type": "boolean"
                }
            }
        },
        "entity_admin.RespToken": {
            "type": "object",
            "properties": {
                "chains": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Chain"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "decimals": {
                    "type": "integer"
                },
                "eos_contract": {
                    "type": "string"
                },
                "evm_contract": {
                    "type": "string"
                },
                "icon_url": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "info": {
                    "$ref": "#/definitions/entity.TokenInfo"
                },
                "name": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "withdraw_fee": {
                    "type": "string"
                }
            }
        },
        "entity_admin.RespUser": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "first_reposit_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_reposit_at": {
                    "type": "string"
                },
                "last_used_at": {
                    "type": "string"
                },
                "last_withdraw_at": {
                    "type": "string"
                },
                "login_method": {
                    "$ref": "#/definitions/db.LoginMethod"
                },
                "passkey_count": {
                    "type": "integer"
                },
                "security_level": {
                    "type": "integer"
                },
                "uid": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfoadmin holds exported Swagger Info so clients can modify it
var SwaggerInfoadmin = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8084",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "exapp-go admin api",
	Description:      "",
	InfoInstanceName: "admin",
	SwaggerTemplate:  docTemplateadmin,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoadmin.InstanceName(), SwaggerInfoadmin)
}
