name: publish-docker-image

on:
  push:
    branches:
      - dev
    tags:
      - 'v*.*.*'

env:
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME || 'exapp/exapp-go' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get version
      id: get_version
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          if (context.ref.startsWith('refs/tags/')) {
            const version = context.ref.replace('refs/tags/', '');
            console.log("Release version:", version);
            return version;
          } else {
            return 'alpha';
          }

    - name: Build the Docker image
      env:
        REPOSITORY_NAME: ${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.result }}
      run: docker build . -t $REPOSITORY_NAME

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push image to Amazon ECR (dev branch)
      if: github.ref == 'refs/heads/dev'
      env: 
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY_NAME: ${{ env.IMAGE_NAME }}:alpha
      run: |
        docker tag $REPOSITORY_NAME $ECR_REGISTRY/$REPOSITORY_NAME
        docker push $ECR_REGISTRY/$REPOSITORY_NAME

    - name: Push image to Amazon ECR (release tag)
      if: startsWith(github.ref, 'refs/tags/')
      env: 
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY_NAME: ${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.result }}
      run: |
        docker tag $REPOSITORY_NAME $ECR_REGISTRY/$REPOSITORY_NAME
        docker push $ECR_REGISTRY/$REPOSITORY_NAME

    